import type { Lead } from "./types"

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    name: "Sarah Johnson",
    phone: "+1 (555) 123-4567",
    email: "sarah.johnson@email.com",
    location: "Los Angeles, CA",
    workType: "Kitchen Renovation",
    conversationSummary: "Customer is looking to renovate their kitchen. They want modern cabinets, quartz countertops, and new appliances. Budget is around $25,000-$35,000. Timeline is flexible but preferably within 3 months.",
    rating: 5,
    ratingReason: "Excellent lead! High budget, in our service area, and work type matches our expertise perfectly.",
    status: "pending",
    source: "whatsapp",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "lead-002",
    name: "Michael Chen",
    phone: "+1 (555) 234-5678",
    email: "m.chen@business.com",
    location: "San Francisco, CA",
    workType: "Commercial Office Build-out",
    conversationSummary: "Business owner needs office space build-out for a new tech startup. Looking for an open floor plan with 4 private offices, a conference room, and a break room. Space is approximately 3,500 sq ft. Needs completion within 6 weeks.",
    rating: 4,
    ratingReason: "Great commercial opportunity. Tight timeline might be challenging but doable.",
    status: "manual",
    source: "email",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "lead-003",
    name: "Emma Wilson",
    phone: "+1 (555) 345-6789",
    email: "emma.w@gmail.com",
    location: "Austin, TX",
    workType: "Bathroom Remodel",
    conversationSummary: "Homeowner wants to remodel master bathroom. Interested in walk-in shower, double vanity, and heated floors. Has seen our previous work on Instagram and loves the modern aesthetic. Budget is $15,000-$20,000.",
    rating: 2,
    ratingReason: "Not in our service area - Austin, TX is outside our coverage zone.",
    status: "pending",
    source: "whatsapp",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "lead-004",
    name: "David Park",
    phone: "+1 (555) 456-7890",
    email: "david.park@outlook.com",
    location: "Seattle, WA",
    workType: "Deck Construction",
    conversationSummary: "Customer wants a new composite deck built in their backyard. Approximately 400 sq ft with built-in seating and lighting. Has HOA approval already. Looking to start in spring.",
    rating: 3,
    ratingReason: "Moderate fit - we do decks but it's not our specialty. Customer is well-prepared.",
    status: "manual",
    source: "whatsapp",
    isLoyal: true,
    leadCount: 3,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "lead-005",
    name: "Lisa Anderson",
    phone: "+1 (555) 567-8901",
    email: "lisa.a@company.org",
    location: "Denver, CO",
    workType: "Home Addition",
    conversationSummary: "Family needs a 600 sq ft home addition for a new nursery and home office. Want it to match existing home exterior. Have architectural plans already drawn up. Budget is $80,000-$100,000.",
    rating: 1,
    ratingReason: "Outside service area and we don't do home additions currently.",
    status: "declined",
    source: "email",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "lead-006",
    name: "James Rodriguez",
    phone: "+1 (555) 678-9012",
    email: "j.rodriguez@techstart.io",
    location: "Portland, OR",
    workType: "Full Home Renovation",
    conversationSummary: "Tech executive looking to completely renovate their 1960s home. Wants to modernize while preserving original character. Interested in smart home integration, open concept living, and sustainable materials. Budget $200K+.",
    rating: 5,
    ratingReason: "Premium client with substantial budget and clear vision. Perfect fit for our expertise.",
    status: "approved",
    source: "whatsapp",
    isLoyal: true,
    leadCount: 5,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: "lead-007",
    name: "Amanda Foster",
    phone: "+1 (555) 789-0123",
    email: "amanda.f@designco.com",
    location: "Miami, FL",
    workType: "Office Interior Design",
    conversationSummary: "Design firm needs a partner for a client office refresh. 2,000 sq ft space with focus on collaborative areas, standing desks, and biophilic design elements. Looking for long-term partnership.",
    rating: 4,
    ratingReason: "Strong project with good potential for ongoing work.",
    status: "approved",
    source: "email",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "lead-008",
    name: "Robert Kim",
    phone: "+1 (555) 890-1234",
    email: "robert.kim@email.com",
    location: "San Diego, CA",
    workType: "Bathroom Upgrade",
    conversationSummary: "Retired couple looking to upgrade their master bathroom for accessibility. Walk-in tub, grab bars, non-slip flooring, and modern vanity. Budget around $25,000.",
    rating: 4,
    ratingReason: "Clear project scope and reasonable expectations.",
    status: "approved",
    source: "whatsapp",
    isLoyal: true,
    leadCount: 4,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "lead-009",
    name: "Michelle Torres",
    phone: "+1 (555) 234-5678",
    email: "michelle.t@startup.co",
    location: "New York, NY",
    workType: "Retail Store Build",
    conversationSummary: "Opening a new boutique fitness studio. Need 1,500 sq ft renovation with mirrored walls, rubber flooring, and reception area. Looking to open in 8 weeks.",
    rating: 3,
    ratingReason: "Good fit but tight timeline may be challenging.",
    status: "manual",
    source: "whatsapp",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: "lead-010",
    name: "Kevin O'Brien",
    phone: "+1 (555) 345-6789",
    email: "kevin.obrien@lawfirm.com",
    location: "Chicago, IL",
    workType: "Law Office Renovation",
    conversationSummary: "Established law firm upgrading their conference rooms and private offices. Need modern AV systems, soundproofing, and ergonomic furniture. Budget $150K.",
    rating: 4,
    ratingReason: "Professional client with clear requirements and good budget.",
    status: "pending",
    source: "email",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "lead-011",
    name: "Priya Sharma",
    phone: "+1 (555) 456-7890",
    email: "priya.s@designstudio.net",
    location: "Boston, MA",
    workType: "Studio Apartment Remodel",
    conversationSummary: "Interior designer looking to gut renovate her own studio apartment. Needs creative storage solutions, Murphy bed, and home office corner. Max budget $40K.",
    rating: 3,
    ratingReason: "Creative project but budget is on the lower end.",
    status: "pending",
    source: "whatsapp",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: "lead-012",
    name: "Thomas Wright",
    phone: "+1 (555) 567-8901",
    email: "t.wright@corp.com",
    location: "Dallas, TX",
    workType: "Corporate HQ Refresh",
    conversationSummary: "Fortune 500 company refreshing their 10,000 sq ft headquarters. Focus on open collaboration spaces, phone booths, and wellness rooms. Multi-phase project.",
    rating: 5,
    ratingReason: "Major corporate project with substantial budget and long-term potential.",
    status: "approved",
    source: "email",
    isLoyal: true,
    leadCount: 6,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
  {
    id: "lead-013",
    name: "Rachel Green",
    phone: "+1 (555) 678-9012",
    email: "rachel.g@boutique.com",
    location: "Nashville, TN",
    workType: "Boutique Store Design",
    conversationSummary: "Entrepreneur opening a boutique clothing store. Needs vintage-modern aesthetic, custom fixtures, and eye-catching window displays. Budget $50K-$75K.",
    rating: 4,
    ratingReason: "Creative project with good budget. Customer has clear vision.",
    status: "manual",
    source: "whatsapp",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: "lead-014",
    name: "Marcus Johnson",
    phone: "+1 (555) 789-0123",
    email: "marcus.j@restaurant.com",
    location: "Phoenix, AZ",
    workType: "Restaurant Interior",
    conversationSummary: "Chef opening a farm-to-table restaurant. Needs warm rustic design, open kitchen concept, and custom bar area. Budget $120K.",
    rating: 2,
    ratingReason: "Large project but restaurant work is not our primary focus.",
    status: "manual",
    source: "email",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: "lead-015",
    name: "Sophia Martinez",
    phone: "+1 (555) 890-1234",
    email: "sophia.m@wellness.io",
    location: "San Diego, CA",
    workType: "Spa Renovation",
    conversationSummary: "Wellness center upgrading to a luxury spa. Needs serene atmosphere, treatment rooms, and meditation space. Budget $80K-$100K.",
    rating: 3,
    ratingReason: "Good budget but requires specialized spa experience we don't have in-house.",
    status: "manual",
    source: "whatsapp",
    isLoyal: true,
    leadCount: 3,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
  },
  {
    id: "lead-016",
    name: "Daniel Lee",
    phone: "+1 (555) 901-2345",
    email: "daniel.lee@startup.com",
    location: "Austin, TX",
    workType: "Co-working Space",
    conversationSummary: "Building a modern co-working space for freelancers. Needs flexible workstations, phone booths, and communal lounge. 3,000 sq ft.",
    rating: 4,
    ratingReason: "Moderate fit - commercial work but timeline is tight.",
    status: "manual",
    source: "email",
    isLoyal: false,
    leadCount: 1,
    autoApproved: false,
    lastContactedAt: null,
    teamId: undefined,
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
]
