import type { Lead, LeadSession } from "./types"

// Mock data for local development when Supabase is not connected
export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    name: "Sarah Johnson",
    phone: "+1 (555) 123-4567",
    email: "sarah.johnson@email.com",
    leadCount: 1,
    isLoyal: false,
    autoApproved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    session: {
      id: "session-001",
      createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      teamsId: "team-001",
      leadsId: "lead-001",
      status: "active",
      currentStep: "completed",
      collectedData: {
        location: "Los Angeles, CA",
        workType: "Kitchen Renovation",
        message: "Customer is looking to renovate their kitchen. They want modern cabinets, quartz countertops, and new appliances. Budget is around $25,000-$35,000. Timeline is flexible but preferably within 3 months.",
        contactPlatform: "whatsapp",
      },
      needsMoreInfo: false,
      rating: true,
      ratingReason: "Excellent lead! High budget, in our service area, and work type matches our expertise perfectly.",
      updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    } as LeadSession,
  },
  {
    id: "lead-002",
    name: "Michael Chen",
    phone: "+1 (555) 234-5678",
    email: "m.chen@business.com",
    leadCount: 3,
    isLoyal: true,
    autoApproved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    session: {
      id: "session-002",
      createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      teamsId: "team-001",
      leadsId: "lead-002",
      status: "active",
      currentStep: "completed",
      collectedData: {
        location: "San Francisco, CA",
        workType: "Commercial Office Build-out",
        message: "Business owner needs office space build-out for a new tech startup. Looking for an open floor plan with 4 private offices, a conference room, and a break room. Space is approximately 3,500 sq ft. Needs completion within 6 weeks.",
        contactPlatform: "email",
      },
      needsMoreInfo: false,
      rating: true,
      ratingReason: "Great commercial opportunity. Tight timeline might be challenging but doable.",
      updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    } as LeadSession,
  },
  {
    id: "lead-003",
    name: "Emma Wilson",
    phone: "+1 (555) 345-6789",
    email: "emma.w@gmail.com",
    leadCount: 1,
    isLoyal: false,
    autoApproved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    session: {
      id: "session-003",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      teamsId: "team-001",
      leadsId: "lead-003",
      status: "active",
      currentStep: "completed",
      collectedData: {
        location: "Austin, TX",
        workType: "Bathroom Remodel",
        message: "Homeowner wants to remodel master bathroom. Interested in walk-in shower, double vanity, and heated floors. Has seen our previous work on Instagram and loves the modern aesthetic. Budget is $15,000-$20,000.",
        contactPlatform: "whatsapp",
      },
      needsMoreInfo: false,
      rating: false,
      ratingReason: "Not in our service area - Austin, TX is outside our coverage zone.",
      updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    } as LeadSession,
  },
  {
    id: "lead-004",
    name: "David Park",
    phone: "+1 (555) 456-7890",
    email: "david.park@outlook.com",
    leadCount: 2,
    isLoyal: false,
    autoApproved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    session: {
      id: "session-004",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
      teamsId: "team-001",
      leadsId: "lead-004",
      status: "active",
      currentStep: "completed",
      collectedData: {
        location: "Seattle, WA",
        workType: "Deck Construction",
        message: "Customer wants a new composite deck built in their backyard. Approximately 400 sq ft with built-in seating and lighting. Has HOA approval already. Looking to start in spring.",
        contactPlatform: "whatsapp",
      },
      needsMoreInfo: false,
      rating: false,
      ratingReason: "Moderate fit - we do decks but it's not our specialty. Customer is well-prepared.",
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    } as LeadSession,
  },
  {
    id: "lead-005",
    name: "Lisa Anderson",
    phone: "+1 (555) 567-8901",
    email: "lisa.a@company.org",
    leadCount: 1,
    isLoyal: false,
    autoApproved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    session: {
      id: "session-005",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      teamsId: "team-001",
      leadsId: "lead-005",
      status: "completed",
      currentStep: "completed",
      collectedData: {
        location: "Denver, CO",
        workType: "Home Addition",
        message: "Family needs a 600 sq ft home addition for a new nursery and home office. Want it to match existing home exterior. Have architectural plans already drawn up. Budget is $80,000-$100,000.",
        contactPlatform: "email",
      },
      needsMoreInfo: false,
      rating: false,
      ratingReason: "Outside service area and we don't do home additions currently.",
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    } as LeadSession,
  },
  {
    id: "lead-006",
    name: "Spam Bot",
    phone: "+1 (555) 999-8888",
    email: "noreply@suspicious.com",
    leadCount: 1,
    isLoyal: false,
    autoApproved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    session: {
      id: "session-006",
      createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      teamsId: "team-001",
      leadsId: "lead-006",
      status: "completed",
      currentStep: "completed",
      collectedData: {
        location: "Unknown",
        workType: "Get Rich Quick",
        message: "You have won a prize! Click here to claim your million dollars! This is definitely not a scam.",
        contactPlatform: "email",
      },
      needsMoreInfo: false,
      rating: false,
      ratingReason: "Obvious spam message, unrelated to our services.",
      updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    } as LeadSession,
  },
]
